language: node_js
node_js:
  - 12.13.1
cache:
  yarn: true
  directories:
    - node_modules
env:
  global:
    - PATH=$HOME/.yarn/bin:$PATH

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash

install:
  - yarn install

script:
  - yarn test

after_success: yarn coverage
